### ISSUE TITLE
To-Do ✅

### ISSUE THREAD

**Issue by gagangulyani** [gagangulyani/IM-LY#1]
# Phase 1

## Divyansh

- [x] AI Model for generating images from plain text

## Gagan

- [x] Backend with FastAPI
- [ ] Connect Dummy AI for Testing API
- [ ] Use template for frontend
- [ ] Connect Backend and frontend
- [ ] Integrate Actual AI with the app

# Phase 2

- [ ] Add Create NFT Button on frontend
- [ ] Add functionality for creating NFTs at backend
